authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('signup/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('logout/', views.logout, name='logout'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('users/', views.users_list, name='users_list'),
	path('users/<str:username>/', views.profile_view, name='profile_view'),
	path('friends/', views.friend_list, name='friend_list'),
	path('users/friend-request/send/<int:id>/', views.send_friend_request, name='send_friend_request'),
	path('users/friend-request/cancel/<int:id>/', views.cancel_friend_request, name='cancel_friend_request'),
	path('users/friend-request/accept/<int:id>/', views.accept_friend_request, name='accept_friend_request'),
	path('users/friend-request/delete/<int:id>/', views.delete_friend_request, name='delete_friend_request'),
	path('users/friend/delete/<int:id>/', views.delete_friend, name='delete_friend'),

]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.message_list_details, name='inbox'),
    path('new-message/<int:id>', views.create_message, name='create-message'),
    path('<int:pk>', views.message_view, name='view-message'),
    path('delete/message/<int:pk>', views.delete_message, name='delete-message'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.posts_feed, name='home'),
    path('user', views.users_profile, name='my-profile'),
    path('like/<int:pk>', views.like, name='post-like'),
    path('new', views.create_post, name='create-post'),
    path('<pk>/update', views.update_post, name='update-post'),
    path('update/<int:pk>', views.update_post, name='update-post'),
    path('delete/<int:pk>', views.post_delete, name='delete'),
    path('comment/<int:pk>', views.post_detail, name='comment'),
    path('<int:pk>', views.post_detail, name='view-post'),
    path('comment/delete/<int:pk>', views.delete_comment, name='delete-comment'),

] 

sma_project/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from authentication.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login, name="home"),
    path('accounts/', include('authentication.urls')),
    path('post/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='authentication/password'
                                                                                   '/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="authentication/password"
                                                                                         "/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='authentication/password'
                                                                              '/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .managers import CustomUserManager
from django.db.models.signals import post_save
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_("Username"), unique=True, max_length=255, null=True, blank=True)
    first_name = models.CharField(_('First Name'), max_length=255, default='user')
    last_name = models.CharField(_('Last Name'), max_length=255, default='user')
    phone = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(_('email address'), unique=True, default='e@email.com')
    avatar = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    user_type = models.CharField(max_length=50, default='user')
    status = models.CharField(max_length=50, default='Active')
    friends = models.ManyToManyField("user", blank=True)
    verified = models.BooleanField(default=False, blank=True)
    occupation = models.CharField(max_length=255, blank=True, null=True)
    company = models.CharField(max_length=255, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    followers_count = models.IntegerField(default=0, editable=False)
    follows_count = models.IntegerField(default=0, editable=False)
    time_zone = models.CharField(max_length=5, default='EST')
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.email

def post_save_user_model_receiver(sender, instance, created, *args, **kwargs):
    if created:
        try:
            User.objects.create(user=instance)
        except:
            pass

post_save.connect(post_save_user_model_receiver, sender=settings.AUTH_USER_MODEL)

class UserSocials(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    linkedin = models.CharField(max_length=255, blank=True, null=True)
    twitter = models.CharField(max_length=255, blank=True, null=True)
    facebook = models.CharField(max_length=255, blank=True, null=True)
    instagram = models.CharField(max_length=255, blank=True, null=True)
    stackoverflow = models.CharField(max_length=255, blank=True, null=True)
    github = models.CharField(max_length=255, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)

    def __str__(self):
        return str(self.user_id)


class Followers(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follows_id')
    follower_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower_id', default=None)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)

    def __str__(self):
        return "From {}, to {}".format(self.user_id, self.follower_id)

authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import logout_then_login
from django.core.exceptions import ValidationError
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.db.models.query_utils import Q
import random
from .models import User, Followers, UserSocials
from posts.models import Posts
from django.contrib.auth.models import auth


def register(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('pwd')
        confirmpwd = request.POST.get('confirmpwd')
        first_name = request.POST.get('firstname')
        last_name = request.POST.get('lastname')
        email = request.POST.get('email')
        bio = request.POST.get('bio')
        phone = request.POST.get('phone')
        avatar = request.POST.get('avatar')
        occupation = request.POST.get('occupation')
        company = request.POST.get('company')

        if password == confirmpwd:
            try:
                user = User.objects.get(email=email)
                messages.info(request, 'Email is already taken')
                return redirect('authentication:register')

            except User.DoesNotExist:
                user = User.objects.create_user(email, username=username, first_name=first_name,
                                                last_name=last_name, password=password, bio=bio, phone=phone,
                                                avatar=avatar, occupation=occupation, company=company)
                user.save()
                user_profile = UserSocials.objects.create(user_id=user)
                auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('authentication:login')
        elif password == "":
            messages.error(request, 'Password field must be filled')
            return redirect('authentication:register')
        else:
            messages.error(request, 'Password must match')
            return redirect('authentication:register')

    return render(request, "authentication/register.html")


@login_required
def update_profile(request):
    user_profile = UserSocials.objects.get(user_id=request.user.id)
    avatar = request.FILES.get('avatar')
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        bio = request.POST.get('bio')
        linkedin = request.POST.get('linkedin')
        twitter = request.POST.get('twitter')
        github = request.POST.get('github')
        stackoverflow = request.POST.get('stackoverflow')
        instagram = request.POST.get('instagram')
        facebook = request.POST.get('facebook')

        try:
            user_profile.user_id.username = username
            user_profile.user_id.email = email
            user_profile.user_id.bio = bio
            user_profile.user_id.avatar = avatar
            user_profile.linkedin = linkedin
            user_profile.twitter = twitter
            user_profile.github = github
            user_profile.stackoverflow = stackoverflow
            user_profile.instagram = instagram
            user_profile.facebook = facebook
            user_profile.user_id.save()
            user_profile.save()
            messages.success(request, f'Profile Updated!')
            return redirect('posts:my-profile')

        except UserSocials.DoesNotExist:
            messages.error('User not found!')

    context = {
        'user_profile': user_profile,
        'user_profile.user_id': user_profile.user_id
    }

    return render(request, 'authentication/edit_profile.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('posts:home')
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = authenticate(email=email, password=password)

            if user is not None:
                auth.login(request, user)
                return redirect('posts:home')
        except ValidationError:
            messages.error(request, 'Unable to reach auth server')
            return redirect("authentication:login")

    return render(request, "authentication/login.html")


def forgot_password(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "authentication/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'SMA App',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@smaapp.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    messages.success(request, 'A message with reset password instructions has been sent to your inbox.')
                    return redirect("authentication:login")
            messages.error(request, 'An invalid email has been entered.')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="authentication/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


def home(request):
    return render(request, "posts/home.html")


def logout(request):
    return logout_then_login(request)

@login_required(login_url='/accounts/login/')
def users_list(request):
    users = User.objects.exclude(user=request.user)
    sent_friend_requests = Followers.objects.filter(user_id=request.user)
    my_friends = request.user.friends.all()
    sent_to = []
    friends = []
    for user in my_friends:
        friend = user.friends.all()
        for f in friend:
            if f in friends:
                friend = friend.exclude(user=f.user)
        friends += friend
    for i in my_friends:
        if i in friends:
            friends.remove(i)
    if request.user in friends:
        friends.remove(request.user)
    random_list = random.sample(list(users), min(len(list(users)), 10))
    for r in random_list:
        if r in friends:
            random_list.remove(r)
    friends += random_list
    for i in my_friends:
        if i in friends:
            friends.remove(i)
    for se in sent_friend_requests:
        sent_to.append(se.follower_id)
    context = {
        'users': friends,
        'sent': sent_to
    }
    return render(request, "authentication/users_list.html", context)

@login_required(login_url='/accounts/login/')
def friend_list(request):
    p = request.user
    friends = p.friends.all()
    context={
	'friends': friends
	}
    return render(request, "authentication/friend_list.html", context)

@login_required(login_url='/accounts/login/')
def send_friend_request(request, id):
    user = get_object_or_404(User, id=id)
    friend_request, created = Followers.objects.get_or_create(
            user_id=request.user,
            follower_id=user)
    return HttpResponseRedirect('/accounts/users/{}'.format(user.username))

@login_required(login_url='/accounts/login/')
def cancel_friend_request(request, id):
    user = get_object_or_404(User, id=id)
    print(user)
    friend_request = Followers.objects.filter(user_id=request.user, follower_id=user).first()
    print(friend_request)
    friend_request.delete()
    return HttpResponseRedirect('/accounts/users/{}'.format(user.username))

@login_required(login_url='/accounts/login/')
def accept_friend_request(request, id):
    from_user = get_object_or_404(User, id=id)
    print(from_user)
    friend_request = Followers.objects.filter(user_id=from_user, follower_id=request.user).first()
    print(friend_request)
    user1 = friend_request.user_id
    print(user1)
    user2 = request.user
    print(user2)
    user1.friends.add(user2.id)
    user2.friends.add(user1.id)
    if(Followers.objects.filter(user_id=request.user, follower_id=from_user).first()):
        request_rev = Followers.objects.filter(user_id=request.user, to_user=from_user).first()
        print(request_rev)
        request_rev.delete()
    friend_request.delete()
    return HttpResponseRedirect('/accounts/users/{}'.format(request.user.username))

@login_required(login_url='/accounts/login/')
def delete_friend_request(request, id):
    from_user = get_object_or_404(User, id=id)
    friend_request = Followers.objects.filter(from_user=from_user, to_user=request.user).first()
    friend_request.delete()
    return HttpResponseRedirect('/accounts/users/{}'.format(request.user.username))

@login_required(login_url='/accounts/login/')
def delete_friend(request, id):
    user_profile = request.user

authentication/templates/authentication/follows.html
<!DOCTYPE html>
<html>
<head>
    <title>Profile Page</title>
</head>
<body>
    <h1>Profile Page</h1>
    <hr>
    {% if user_obj.name == request.session.user%}
    <h4>Name: {{user_obj.name}}</h4>
    <span>Followers: {{followers.count }}</span>
    <br>
    <span>Following: {{session_following.another_user.count }}</span>
    {% else %}
    <h4>Name: {{user_obj.name}}</h4>
    <span>Followers: {{followers.count }}</span>
    <br>
    <span>Following: {{user_following.another_user.count }}</span>
    <h4>Profile is Private.</h4>
    {% endif %}
    <br><br>

    {% if user_obj.name != request.session.user%}
    {% if is_followed %}
        <a href="{% url 'follow' user_obj.name %}" style="border: 1px solid; background: red; padding:10px; color: white;">Unfollow</a>
    {% else %}
        <a href="{% url 'follow' user_obj.name %}" style="border: 1px solid; background: yellow; padding:10px; color: black;">Follow</a>
    {% endif %}

    {% endif %}
</body>
</html>

authentication/templates/authentication/friend_list.html
{% extends "authentication/header.html" %} {% load static %}  {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      {% if friends %}
      <div class="card card-signin my-5">
        <div class="card-body">
          {% for user_p in friends %}
          <a href="{{ user_p.get_absolute_url }}"
            ><img
              src="{{ user_p.avatar.url }}"
              class="rounded mr-2"
              width="40"
              height="40"
              alt=""
          /></a>
          <a class="text-dark" href="{{ user_p.get_absolute_url }}"
            ><b>{{ user_p.username }}</b></a
          >
          <small
            ><a
              class="btn btn-danger float-right"
              href="{% url 'authentication:delete_friend' user_p.id %}"
              >UnFriend</a
            ></small
          >
          <br /><br />
          {% endfor %}
        </div>
      </div>
      {% else %}
      <h5>
        <i
          >You have no friends now! Make some new
          <a href="{% url 'authentication:users_list' %}">friends here!</a></i
        >
      </h5>
      {% endif %}
    </div>
  
  </div>
  {% endblock content %}
</div>

authentication/templates/authentication/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <script
      src="https://kit.fontawesome.com/a20c4e6c94.js"
      crossorigin="anonymous"
    ></script>
    <meta charset="UTF-8" />
    <meta name="description" content="Profile Page" />
    <meta name="keywords" content="HTML, CSS" />
    <meta name="author" content="Mimi Mahamah" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'profile/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/layout.css' %}" >
  </head>
  <title>Profile Page</title>

  <body>
    <header>
      <img id="triangles" src="{% static 'profile/TRIANGLES.png' %}" alt="" />
      <ul class="menu">
        <li class="menu__item">
          <a href="{% url 'posts:home' %}"
            ><i class="fas fa-home"></i><strong id="inbox">Home</strong></a
          >
        </li>

        <li class="menu__item">
          <a href="{% url 'posts:create-post' %}"
            ><i class="fas fa-user-friends"></i
            ><strong id="inbox"> Create Posts</strong></a
          >
        </li>
        <li class="menu__item">
          <a href="{% url 'chat:inbox' %}"
            ><i class="fas fa-envelope"></i><strong id="inbox">Inbox</strong></a
          >
        </li>
        <li class="menu__item">
          <a href="{% url 'authentication:profile_view' user.username %}"
            ><i class="fas fa-user"></i><strong id="foll">Profile</strong></a
          >
        </li>
        <li class="menu__item">
          <a href="{% url 'authentication:logout' %}"
            ><i class="fas fa-sign-out-alt"></i><strong id="foll"></strong
          ></a>
        </li>
      </ul>
      {% if user.avatar%}
     <img
          id="profile"
          src="{{ user.avatar.url }}"
          alt="profile picture"
      />
      {% else %}
     ><img
          id="profile"
          src="{% static 'profile/user-avatar.png' %}"
          alt="profile picture"
      />
      {% endif %}
    </header>
    {% for message in messages %} {% if message.error %}
    <div class="alert error">
      <input type="checkbox" id="alert1" />
      <label class="close" title="close" for="alert1">
        <i class="icon-remove"></i>
      </label>
      <p class="inner">{{ message }}</p>
    </div>
    {% elif message.tags == 'success' %}
    <div class="alert success">
      <input type="checkbox" id="alert2" />
      <label class="close" title="close" for="alert2">
        <i class="icon-remove"></i>
      </label>
      <p class="inner">{{ message }}</p>
    </div>
    {% elif message.tags == 'info' %}
    <div class="alert info">
      <input type="checkbox" id="alert3" />
      <label class="close" title="close" for="alert3">
        <i class="icon-remove"></i>
      </label>
      <p class="inner">{{ message }}</p>
    </div>
    {% elif message.tags == 'warning' %}
    <div class="alert warning">
      <input type="checkbox" id="alert4" />
      <label class="close" title="close" for="alert4">
        <i class="icon-remove"></i>
      </label>
      <p class="inner">{{ message }}</p>
    </div>

    {% else %}
    <div class="alert">
      <input type="checkbox" id="alert5" />
      <label class="close" title="close" for="alert5">
        <i class="icon-remove"></i>
      </label>
      <p class="inner">{{ message }}</p>
    </div>
    {% endif %} {% endfor %}
    <div class="container">{% block content %} {% endblock %}</div>
    {% block jsfiles %}
    {% endblock jsfiles %}
  </body>
</html>

authentication/templates/authentication/user_profile.html
{% extends "authentication/header.html" %} {% load static %}  {% block content %}
<br /><br />
<div class="main-content">
  <div class="container mt-7">
    <div class="row">
      <div class="col-xl-8 m-auto order-xl-2 mb-5 mb-xl-0">
        <div class="card card-profile shadow">
          <div class="row justify-content-center">
            <div class="col-lg-3 order-lg-2">
              <div class="card-profile-image">
                {% if u.avatar%}
                <a href="{{ u.avatar.url }}">
                  <img
                    src="{{ u.avatar.url }}"
                    class="rounded-circle"
                    width="160px"
                    height="160px"
                  />
                </a>
                {% else %}
                <a href="{{ u.avatar.url }}">
                  <img
                    src="{% static 'profile/user-avatar.png'%}"
                    class="rounded-circle"
                    width="160px"
                    height="160px"
                  />
                </a>
                {% endif %}
              </div>
            </div>
          </div>
          <div
            class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4"
          ></div>
          <div class="card-body pt-0 pt-md-4">
            <div class="row">
              <div class="col">
                <div
                  class="card-profile-stats d-flex justify-content-center mt-md-5"
                >
                  <div>
                    <span class="heading">{{ user.friends.count }}</span>
                    {% if request.user.id == u %}
                    <span class="description"
                      ><a href="{% url 'authentication:friend_list' %}">Friends</a></span
                    >
                    {% else %}
                    <span class="description">Friends</span>
                    {% endif %}
                    <span class="heading">{{ post_count }}</span>
                    <span class="description"
                      ><a href="{% url 'posts:my-profile' %}"
                        >Posts</a
                      ></span
                    >
                    <span class="description"
                      ><a href="{% url 'chat:create-message' u %}"
                        >Chat</a
                      ></span
                    >
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center">
              <h3>{{ u.username }}</h3>
              <p>{{ u.bio }}</p>
              <hr class="my-2" />
              {% if request.user.id == u %}
              <a class="btn btn-info" href="{% url 'authentication:update-profile' %}"
                >Update Profile</a
              >
              {% else %} {% if button_status == 'not_friend' %}
              <small
                ><a
                  class="btn btn-primary"
                  href="{% url 'authentication:send_friend_request' u %}"
                  >Add Friend</a
                ></small
              >
              {% elif button_status == 'friend_request_sent' %}
              <small
                ><a
                  class="btn btn-warning"
                  href="{% url 'authentication:cancel_friend_request' u %}"
                  >Cancel Request</a
                ></small
              >
              {% elif button_status == 'friend_request_received' %}
              <small
                ><a
                  class="btn btn-success mr-2"
                  href="{% url 'authentication:accept_friend_request' u %}"
                  >Accept Request</a
                ></small
              >
              <small
                ><a
                  class="btn btn-danger"
                  href="{% url 'authentication:delete_friend_request' u %}"
                  >Reject Request</a
                ></small
              >
              {% else %}
              <small
                ><a
                  class="btn btn-danger"
                  href="{% url 'authentication:delete_friend' u %}"
                  >UnFriend</a
                ></small
              >
              {% endif %} {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <br />
    {% if request.user.id == u %}
    <div class="row">
      <div class="col-md-6">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h2>Friend Requests Sent ({{ sent_friend_requests.count }})</h2>
            <hr class="my-2" />
            {% if not sent_friend_requests %}
            <h5><i>No sent requests!</i></h5>
            {% else %} {% for s_request in sent_friend_requests %}
            {% if s_request.follower_id.avatar %}
            <a href="{{ s_request.to_user.profile.get_absolute_url }}"
              ><img
                src="{{ s_request.follower_id.avatar.url }}"
                class="rounded mr-2"
                width="40"
                height="40"
                alt=""
            /></a>
            {% else %}
            <a href="{{ s_request.to_user.profile.get_absolute_url }}"
              ><img
                src="{% static 'profile/user-avatar.png'%}"
                class="rounded mr-2"
                width="40"
                height="40"
                alt=""
            /></a>
            {% endif %}
            <a href="{{ s_request.to_user.profile.get_absolute_url }}"
              ><b>{{ s_request.follower_id.username }}</b></a
            >
            <small class="float-right">
                <br>
              <a
                class="btn btn-warning mr-2"
                href="{% url 'authentication:cancel_friend_request' s_request.follower_id.id %}"
                >Cancel</a
              >
            </small>
            <br /><br />
            {% endfor %} {% endif %}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h2>Friend Requests Received ({{ rec_friend_requests.count }})</h2>
            <hr class="my-2" />
            {% if not rec_friend_requests %}
            <h5><i>No received requests!</i></h5>
            {% else %} {% for r_request in rec_friend_requests %}
            {% if r_request.user_id.avatar %}
            <a href="{{ r_request.user_id.avatar.get_absolute_url }}"
              ><img
                src="{{ r_request.user_id.avatar.url }}"
                class="rounded mr-2"
                width="40"
                height="40"
                alt=""
            /></a>
            {% else %}
            <a href="{{ r_request.user_id.avatar.get_absolute_url }}"
              ><img
                src="{% static 'profile/user-avatar.png'%}"
                class="rounded mr-2"
                width="40"
                height="40"
                alt=""
            /></a>
            {% endif %}
            <a
              class="mr-2 align-middle"
              href="{{ r_request.from_user.profile.get_absolute_url }}"
              ><b>{{ r_request.user_id.username }}</b>
            </a>
            <br>
            <small class="float-right">
              <a
                class="btn btn-success mr-2"
                href="{% url 'authentication:accept_friend_request' r_request.user_id.id %}"
                >Accept</a
              >
              <a
                class="btn btn-danger"
                href="/users/friend-request/delete/{{ r_request.from_user.id }}"
                >Reject</a
              >
            </small>
            <br /><br />
            {% endfor %} {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>

{% endblock content %}