authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('signup/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('logout/', views.logout, name='logout'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('users/', views.users_list, name='users_list'),
	path('users/<str:username>/', views.profile_view, name='profile_view'),
	path('friends/', views.friend_list, name='friend_list'),
	path('users/friend-request/send/<int:id>/', views.send_friend_request, name='send_friend_request'),
	path('users/friend-request/cancel/<int:id>/', views.cancel_friend_request, name='cancel_friend_request'),
	path('users/friend-request/accept/<int:id>/', views.accept_friend_request, name='accept_friend_request'),
	path('users/friend-request/delete/<int:id>/', views.delete_friend_request, name='delete_friend_request'),
	path('users/friend/delete/<int:id>/', views.delete_friend, name='delete_friend'),

]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.message_list_details, name='inbox'),
    path('new-message/<int:id>', views.create_message, name='create-message'),
    path('<int:pk>', views.message_view, name='view-message'),
    path('delete/message/<int:pk>', views.delete_message, name='delete-message'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('dummy-social', views.home, name='dummy-social'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

sma_project/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from authentication.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login, name="home"),
    path('accounts/', include('authentication.urls')),
    path('post/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='authentication/password'
                                                                                   '/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="authentication/password"
                                                                                         "/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='authentication/password'
                                                                              '/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import redirect, render

# Create your views here.

def home(request):
    return render(request, 'home/dummysocialfeed.html')

home/templates/home/login-in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Epilogue:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../css/log-in.css">
    <title>Log In</title>
</head>
<body id="layout">
    <main>
        <section class="welcome-cont">
            <div class="mobile-polygons">
                <div class="poly-12-g2"><img src="../mobile-polygons/poly-group4/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-11-g2"><img src="../mobile-polygons/poly-group4/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-9-g2"><img src="../mobile-polygons/poly-group4/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-10-g2"><img src="../mobile-polygons/poly-group4/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-8-g2"><img src="../mobile-polygons/poly-group4/polygon 8.svg" alt="purple polygon"></div>
                <!--GROUP 2 POLYGONS-->
                <div class="poly-12-g4"><img src="../mobile-polygons/poly-group2/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-11-g4"><img src="../mobile-polygons/poly-group2/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-9-g4"><img src="../mobile-polygons/poly-group2/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-10-g4"><img src="../mobile-polygons/poly-group2/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-8-g4"><img src="../mobile-polygons/poly-group2/polygon 8.svg" alt="purple polygon"></div>
                <!--MIDDLE POLYGONS-->
                <div class="poly-12-mid"><img src="../mobile-polygons/polygons/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-11-mid"><img src="../mobile-polygons/polygons/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-9-mid"><img src="../mobile-polygons/polygons/Polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-10-mid"><img src="../mobile-polygons/polygons/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-8-mid"><img src="../mobile-polygons/polygons/polygon 8.svg" alt="purple polygon"></div>
            </div>
            <div class="desktop-polygons">
                <div class="poly-desktop-12-g2"><img src="../desktop-polygons/poly-group4/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-desktop-11-g2"><img src="../desktop-polygons/poly-group4/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-desktop-9-g2"><img src="../desktop-polygons/poly-group4/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-desktop-10-g2"><img src="../desktop-polygons/poly-group4/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-desktop-8-g2"><img src="../desktop-polygons/poly-group4/polygon 8.svg" alt="purple polygon"></div>
                <!--GROUP 2 POLYGONS-->
                <div class="poly-desktop-12-g4"><img src="../desktop-polygons/poly-group2/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-desktop-11-g4"><img src="../desktop-polygons/poly-group2/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-desktop-9-g4"><img src="../desktop-polygons/poly-group2/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-desktop-10-g4"><img src="../desktop-polygons/poly-group2/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-desktop-8-g4"><img src="../desktop-polygons/poly-group2/polygon 8.svg" alt="purple polygon"></div>
                <!--MIDDLE POLYGONS-->
                <div class="poly-desktop-12-mid"><img src="../desktop-polygons/polygons/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-desktop-11-mid"><img src="../desktop-polygons/polygons/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-desktop-9-mid"><img src="../desktop-polygons/polygons/Polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-desktop-10-mid"><img src="../desktop-polygons/polygons/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-desktop-8-mid"><img src="../desktop-polygons/polygons/polygon 8.svg" alt="purple polygon"></div>
            </div>
            <h1 class="desktop-h1">WELCOME</br> TO SMA </h1>
            <h1 class="mobile-h1">WELCOME TO SMA</h1>
            <h3 class="mobile-h3">PLEASE LOGIN BELOW</h3>
        </section>
            <!--FORM------------>
        <section class="form-cont">
            <h1 class="desktop-h1">LOGIN TO GET STARTED</h1>
            
            <form action="{% url 'authentication:login' %}" method="POST" id="sign_form">
                <div class="form-group">
                 <label for="pwd">E-MAIL ADDRESS</label>
                    <div class="input-cont">
                        <div class="img-cont">
                            <img src="/authentication/logIn-Register/icons/Vector-user.svg" alt="email icon">
                        </div> 
                        <input type="text" name="email" class="form-control input" placeholder="">
                    </div>
                 </div>
                <div class="form-group">
                    <label for="pwd">PASSWORD</label>
                    <div class="input-cont">
                        <div class="img-cont">
                            <img src="/authentication/logIn-Register/icons/Vector2.svg" alt="lock icon">
                        </div> 
                        <input type="password" name="password" class="form-control input"  value="">
                    </div>
                </div>
                    <div class="btn-cont">
                        <button type="submit" class="log">LOGIN</button>
                    </div>
                    <small>NEW USER?<a href="{% url 'authentication:register' %}" class="text-center">REGISTER</a>HERE</small>
            </form>
                <br><br>
                <form action="{% url 'authentication:forgot_password' %}" method="POST" id="PasswordResetForm">
                    <button type="submit" class="btn-block primary-btn">Forgot Password</button>
                </form>
         <section>
    </main>
</body>
</html>

home/templates/home/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Epilogue:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../css/register.css">
    <title>Register</title>
</head>
<body id="layout">
    <main>
        <section class="welcome-cont">
            <div class="mobile-polygons">
                <div class="poly-12-g2"><img src="../register-mobile-poly/poly-group4/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-11-g2"><img src="../register-mobile-poly/poly-group4/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-9-g2"><img src="../register-mobile-poly/poly-group4/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-10-g2"><img src="../register-mobile-poly/poly-group4/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-8-g2"><img src="../register-mobile-poly/poly-group4/polygon 8.svg" alt="purple polygon"></div>
                <!--GROUP 2 POLYGONS-->
                <div class="poly-12-g4"><img src="../register-mobile-poly/poly-group2/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-11-g4"><img src="../register-mobile-poly/poly-group2/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-9-g4"><img src="../register-mobile-poly/poly-group2/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-10-g4"><img src="../register-mobile-poly/poly-group2/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-8-g4"><img src="../register-mobile-poly/poly-group2/polygon 8.svg" alt="purple polygon"></div>
                <!--MIDDLE POLYGONS-->
                <div class="poly-12-mid"><img src="../register-mobile-poly/polygons/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-11-mid"><img src="../register-mobile-poly/polygons/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-9-mid"><img src="../register-mobile-poly/polygons/Polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-10-mid"><img src="../register-mobile-poly/polygons/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-8-mid"><img src="../register-mobile-poly/polygons/polygon 8.svg" alt="purple polygon"></div>
            </div>
            <div class="desktop-polygons">
                <div class="poly-desktop-12-g2"><img src="../desktop-polygons/poly-group4/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-desktop-11-g2"><img src="../desktop-polygons/poly-group4/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-desktop-9-g2"><img src="../desktop-polygons/poly-group4/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-desktop-10-g2"><img src="../desktop-polygons/poly-group4/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-desktop-8-g2"><img src="../desktop-polygons/poly-group4/polygon 8.svg" alt="purple polygon"></div>
                <!--GROUP 2 POLYGONS-->
                <div class="poly-desktop-12-g4"><img src="../desktop-polygons/poly-group2/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-desktop-11-g4"><img src="../desktop-polygons/poly-group2/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-desktop-9-g4"><img src="../desktop-polygons/poly-group2/polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-desktop-10-g4"><img src="../desktop-polygons/poly-group2/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-desktop-8-g4"><img src="../desktop-polygons/poly-group2/polygon 8.svg" alt="purple polygon"></div>
                <!--MIDDLE POLYGONS-->
                <div class="poly-desktop-12-mid"><img src="../desktop-polygons/polygons/polygon 12.svg" alt="blue polygon"></div>
                <div class="poly-desktop-11-mid"><img src="../desktop-polygons/polygons/polygon 11.svg" alt="yellow polygon"></div>
                <div class="poly-desktop-9-mid"><img src="../desktop-polygons/polygons/Polygon 9.svg" alt="orange polygon"></div>
                <div class="poly-desktop-10-mid"><img src="../desktop-polygons/polygons/polygon 10.svg" alt="dark blue polygon"></div>
                <div class="poly-desktop-8-mid"><img src="../desktop-polygons/polygons/polygon 8.svg" alt="purple polygon"></div>
            </div>
            <h3 class="mobile-h3">REGISTER TO JOIN US!</h3>
        </section>
            <!--FORM------------>
        <section class="form-cont">
            <h1 class="desktop-h1">REGISTER TO JOIN US!</h1>
            <form action="{% url 'authentication:login' %}" method="POST" id="sign_form">
                <div class="form-group">
                    <label for="pwd">FIRST NAME</label>
                       <div class="input-cont">
                           <div class="img-cont">
                               <img src="/authentication/logIn-Register/icons/Vector-user.svg" alt="user icon">
                           </div> 
                           <input type="text" name="firstname" class="form-control input" placeholder="">
                       </div>
                </div>
                <div class="form-group">
                 <label for="pwd">LAST NAME</label>
                       <div class="input-cont">
                           <div class="img-cont">
                               <img src="/authentication/logIn-Register/icons/Vector-user.svg" alt="user icon">
                           </div> 
                            <input type="text" name="lastname" class="form-control input" placeholder="">
                       </div>
                </div>
                <div class="form-group">
                    <label for="pwd">USERNAME</label>
                          <div class="input-cont">
                              <div class="img-cont">
                                  <img src="/authentication/logIn-Register/icons/Vector-user.svg" alt="user icon">
                              </div> 
                               <input type="text" name="username" class="form-control input" placeholder="">
                          </div>
                   </div>
                <div class="form-group">
                 <label for="pwd">E-MAIL ADDRESS</label>
                    <div class="input-cont">
                        <div class="img-cont">
                            <img src="/authentication/logIn-Register/icons/Vector.svg" alt="email icon">
                        </div> 
                        <input type="email" name="email" class="form-control input" placeholder="">
                    </div>
                 </div>
                <div class="form-group">
                    <label for="pwd">PASSWORD</label>
                    <div class="input-cont">
                        <div class="img-cont">
                            <img src="/authentication/logIn-Register/icons/Vector2.svg" alt="lock icon">
                        </div> 
                        <input type="password" name="pwd" class="form-control input"  value="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="pwd">CONFIRM PASSWORD</label>
                    <div class="input-cont">
                        <div class="img-cont">
                            <img src="/authentication/logIn-Register/icons/Vector2.svg" alt="lock icon">
                        </div> 
                        <input type="password" name="confirmpwd" class="form-control input"  value="">
                    </div>
                </div>
                    <div class="btn-cont">
                        <button type="submit" class="log">REGISTER</button>
                    </div>
                    <small>ALREADY HAVE AN ACCOUNT?<a href="{% url 'authentication:register' %}" class="text-center">LOG IN</a></small>
            </form>
         <section>
    </main>
</body>
</html>