chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.message_list_details, name='inbox'),
    path('new-message/<int:id>', views.create_message, name='create-message'),
    path('<int:pk>', views.message_view, name='view-message'),
    path('delete/message/<int:pk>', views.delete_message, name='delete-message'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.posts_feed, name='home'),
    path('user', views.users_profile, name='my-profile'),
    path('like/<int:pk>', views.like, name='post-like'),
    path('new', views.create_post, name='create-post'),
    path('<pk>/update', views.update_post, name='update-post'),
    path('update/<int:pk>', views.update_post, name='update-post'),
    path('delete/<int:pk>', views.post_delete, name='delete'),
    path('comment/<int:pk>', views.post_detail, name='comment'),
    path('<int:pk>', views.post_detail, name='view-post'),
    path('comment/delete/<int:pk>', views.delete_comment, name='delete-comment'),

] 

sma_project/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from authentication.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login, name="home"),
    path('accounts/', include('authentication.urls')),
    path('post/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='authentication/password'
                                                                                   '/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="authentication/password"
                                                                                         "/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='authentication/password'
                                                                              '/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.contrib.auth.models import User
from django.db import models
import authentication.models as a


class Message(models.Model):
    sender = models.ForeignKey(a.User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(a.User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    message_thread = models.ForeignKey('MessageThread', related_name='+', on_delete=models.CASCADE, null=True,
                                       blank=True, default=None)
    image = models.ImageField(blank=True, null=True, upload_to='messages/')
    read_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('created_at',)


class MessageThread(models.Model):
    sender = models.ForeignKey(a.User, on_delete=models.CASCADE, related_name='send')
    receiver = models.ForeignKey(a.User, on_delete=models.CASCADE, related_name='receive')
    unread_message = models.BooleanField(null=True, blank=True, default=False)

chat/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = Message
        fields = ['receiver', 'message', 'image']

chat/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from .models import MessageThread, Message

User = get_user_model()

@login_required(login_url='/accounts/login/')
def message_list_details(request):
    messages = Message.objects.filter(Q(sender_id=request.user.id) | Q(receiver_id=request.user.id))
    context = {
        'chats': messages
    }
    return render(request, 'chat/inbox.html', context)

@login_required(login_url='/accounts/login/')
def create_message(request, id):
    sender = User.objects.get(id=request.user.id)
    if request.method == 'GET':
        user = User.objects.get(id=id)
        username = user.username
        if username is None or username == '':
            return redirect('posts:home')
        context = {
            'receiver': username
        }
        return render(request, 'chat/create_message.html', context)

    if request.method == 'POST':
        sender = User.objects.get(id=request.user.id)
        message = request.POST.get('message')
        username = request.POST.get('receiver')
        image = request.FILES.get('image')

        if username == '' or message == '':
            return redirect('chat:create-message')

        try:
            receiver = User.objects.get(username=username)
            if sender.username != receiver.username:
                image = image
                new_message = Message(sender=sender, receiver=receiver,
                                      message=message, image=image)
                new_message.save()
                messages.success(request, 'Message Sent!')
                return redirect('posts:home')
            messages.error(request, 'Message cant be sent to self!')
            return redirect('posts:home')

        except User.DoesNotExist:
            messages.error('Cannot find user!')


def message_view(request, pk):
    message = Message.objects.order_by('-created_at').get(pk=pk)
    if message.read_at is None:
        message.read_at = datetime.datetime.now()
        message.save()

    context = {
        'message': message,
    }
    return render(request, 'chat/message_thread.html', context)


def delete_message(request, pk):
    message = get_object_or_404(Message, pk=pk)
    if message.receiver == request.user:
        message.delete()
        return redirect('chat:inbox')
    return redirect('chat:inbox')

chat/templates/chat/create_message.html
{% extends 'authentication/header.html' %}{% block content %} {% load static %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

<body id="layout">
<!-- Main body goes here -------->

            <!--FORM------------>
        <section class="form-cont">
            <h1 class="desktop-h1">Messages</h1>
            <form action="{% url 'chat:create-message' user.id %}" method="POST" id="sign_form" enctype="multipart/form-data">
                {% csrf_token %}
<!--                <div class="form-group">-->
<!--                    <label for="pwd">RECEIVER</label>-->
<!--                          <div class="input-cont">-->
<!--                              <div class="img-cont">-->
<!--                                  <img src="{% static 'icons/Vector-user.svg' %}" alt="user icon">-->
<!--                              </div>-->
<!--                               <input type="text" name="receiver" class="form-control input" value="{{ receiver }}">-->
<!--                          </div>-->
<!--                   </div>-->

                <input type="hidden" value="{{ receiver }}" name="receiver" id="receiver"/>

                <div class="form-group">
                 <label for="pwd">MESSAGE</label>
                    <div class="input-cont">
                        <div class="img-cont">
                            <img src="{% static 'icons/Vector.svg' %}" alt="email icon">
                        </div>
                        <input type="text-area" name="message" class="form-control input" >
                    </div>
                 </div>
                  <div class="form-group">
            <label for="pwd">IMAGE</label>
                    <div class="input-cont">
                        <div class="img-cont">
                            <img src="{% static 'icons/Vector.svg' %}" alt="phone icon">
                        </div>
            <input type="file" name="image" class="form-control" placeholder="image" accept="image/*" />
                    </div>
          </div>

                             <button type="submit" class="log">SEND</button>
                    <small>GO BACK<a href="{% url 'posts:home' %}" class="text-center"> HOME </a></small>

                    </div>
            </form>
        </section>
</body>
{% endblock %}
{% block jsfiles %}
<script type="text/javascript">
var receiver=localStorage.getItem("receiver");

</script>
{% endblock jsfiles %}

chat/templates/chat/delete_message.html
{% extends 'authentication/header.html' %}{% block content %}
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you sure you want to delete this message?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

{% endblock %}

chat/templates/chat/inbox.html
{% extends 'authentication/header.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12 p-5">
      <h3>Your Messages</h3>
    </div>
    <div class="row">
      <div class="col-md-12 p-5">
        <form method="GET" action="">
          <br>
          <button class="btn btn-light p-3" type="submit">Start New Message</button>
        </form>
      </div>
    </div>
    {% for chat in chats.all %}
    <br>
    <div class="row mb-3">
      <div class="card col-md-12 p-5 shadow-sm">
        <h4>Sender: {{ chat.sender.username }} </h4>
        <br>

        {% if chat.read_at %}
        <h5>read </h5>
        {% else %}
        <h5>unread</h5>
        {% endif %}
        <a class="stretched-link" href="{% url 'chat:view-message' chat.id %}"> View</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

chat/templates/chat/message_thread.html
{% extends 'authentication/header.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <div class="row">
    <div class="card col-md-12 mt-5 p-3 shadow-sm">
      <h5>@{{ message.sender.username }} 
        <a class="btn btn-light" href="">Send Message</a>
      </h5>
      
    </div>
  </div>
  {% if message.all.count == 0 %}
  <div class="row my-5">
    <div class="col-md-12">
      <p class="empty-text">No Messages</p>
    </div>
  </div>
  {% else %}
  <div class="row">
    <div class="col-md-12 my-1">
      <div class="sent-message my-3">
        <p>{{ message.message }}</p>
        {% if message.image %}
        <img src="{{message.image.url}}" alt="" width=150px height=150px>
        {% else %}
        <img alt="" width=0px height=0px>
        {% endif %}
      </div>
      <div class="received-message my-3">
        <p>Sent: {{ message.created_at }}</p>
      </div>
    </div>
  </div>
  {% endif %}
  <a href="{% url 'chat:delete-message' message.id %}"> Delete Message</a>
  <button onclick="goBack()">Go Back</button>
</div>
{% endblock content %}

{% block jsfiles %}
<script>
  function goBack() {
    window.history.back();
  }
  </script>
  {% endblock jsfiles %}