authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('signup/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('logout/', views.logout, name='logout'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('users/', views.users_list, name='users_list'),
	path('users/<str:username>/', views.profile_view, name='profile_view'),
	path('friends/', views.friend_list, name='friend_list'),
	path('users/friend-request/send/<int:id>/', views.send_friend_request, name='send_friend_request'),
	path('users/friend-request/cancel/<int:id>/', views.cancel_friend_request, name='cancel_friend_request'),
	path('users/friend-request/accept/<int:id>/', views.accept_friend_request, name='accept_friend_request'),
	path('users/friend-request/delete/<int:id>/', views.delete_friend_request, name='delete_friend_request'),
	path('users/friend/delete/<int:id>/', views.delete_friend, name='delete_friend'),

]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.message_list_details, name='inbox'),
    path('new-message/<int:id>', views.create_message, name='create-message'),
    path('<int:pk>', views.message_view, name='view-message'),
    path('delete/message/<int:pk>', views.delete_message, name='delete-message'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('dummy-social', views.home, name='dummy-social'),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.posts_feed, name='home'),
    path('user', views.users_profile, name='my-profile'),
    path('like/<int:pk>', views.like, name='post-like'),
    path('new', views.create_post, name='create-post'),
    path('<pk>/update', views.update_post, name='update-post'),
    path('update/<int:pk>', views.update_post, name='update-post'),
    path('delete/<int:pk>', views.post_delete, name='delete'),
    path('comment/<int:pk>', views.post_detail, name='comment'),
    path('<int:pk>', views.post_detail, name='view-post'),
    path('comment/delete/<int:pk>', views.delete_comment, name='delete-comment'),

] 

sma_project/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from authentication.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login, name="home"),
    path('accounts/', include('authentication.urls')),
    path('post/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='authentication/password'
                                                                                   '/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="authentication/password"
                                                                                         "/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='authentication/password'
                                                                              '/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.urls import reverse

import authentication.models as a


class PostCategory(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)

    def __str__(self):
        if self.name is None:
            return 'Post name is empty'
        return self.name


class Posts(models.Model):
    user_id = models.ForeignKey(a.User, on_delete=models.CASCADE)
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to='posts/')
    status = models.CharField(max_length=255, blank=True, null=True)
    like_count = models.IntegerField(default=0, editable=False)
    comment_count = models.IntegerField(default=0, editable=False)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)

    def __str__(self):
        return str(self.user_id)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class PostComments(models.Model):
    user_id = models.ForeignKey(a.User, related_name='details', on_delete=models.CASCADE)
    post_id = models.ForeignKey(Posts, related_name='details', on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='posts/')
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)


class PostLikes(models.Model):
    liker_id = models.ForeignKey(a.User, related_name='likes', on_delete=models.CASCADE)
    post_id = models.ForeignKey(Posts, related_name='likes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)

posts/forms.py
from django import forms
from .models import Posts, PostComments


class NewPostForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = Posts
        fields = ['content', 'image', 'category']


class UpdatePostForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = Posts
        fields = ['content', 'image', 'category']

    def save(self, commit=True):
        post = self.instance
        post.content = self.cleaned_data['content']
        post.category = self.cleaned_data['category']

        if self.cleaned_data['image']:
            post.image = self.cleaned_data['image']
        if commit:
            post.save()
        return post


class NewCommentForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = PostComments
        fields = ['content', 'image']

home/views.py
from django.shortcuts import redirect, render

# Create your views here.

def home(request):
    return render(request, 'home/dummysocialfeed.html')

posts/views.py
import json

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from authentication.models import UserSocials

from .forms import NewPostForm, UpdatePostForm, NewCommentForm
from .models import Posts, PostLikes, PostComments

User = get_user_model()

@login_required(login_url='/accounts/login/')
def posts_feed(request):
    posts = Posts.objects.order_by('-created_at').all()
    liked = [i for i in Posts.objects.all() if PostLikes.objects.filter(liker_id=request.user, post_id=i)]
    form = NewPostForm()
#    if request.method == 'POST':
#       create_post(request)
    context = {
        'form': form,
        'posts': posts,
        'liked_post': liked
    }
    return render(request, 'posts/home.html', context)


@login_required(login_url='/accounts/login/')
def users_profile(request):
    user = User.objects.get(id=request.user.id)
    post = Posts.objects.filter(user_id=user)
    context = {
        'posts': post
    }
    return render(request, 'posts/user_post.html', context)


@login_required(login_url='/accounts/login/')
def create_post(request):
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.user_name = user
            data.user_id = user
            data.save()
            messages.success(request, f'Posted Successfully')
            return redirect('posts:home')
    else:
        form = NewPostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required(login_url='/accounts/login/')
def post_detail(request, pk):
    post = get_object_or_404(Posts, pk=pk)
    print(post.image)
    user = User.objects.get(id=request.user.id)
    comment = PostComments.id
    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.post_id = post
            data.username = user
            data.user_id = user
            data.save()
            if post.id == user.id:
                return redirect('posts:my-profile')
            else:
                return redirect('posts:home')
    else:
        form = NewCommentForm()
    return render(request, 'posts/post_detail.html', {'post': post, 'form': form, 'comment': comment})


@login_required(login_url='/accounts/login/')
def update_post(request, pk):
    post = get_object_or_404(Posts, pk=pk)
    if request.method == "POST":
        form = UpdatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            messages.success(request, f'Post Saved Successfully')
            post = data
            return redirect('posts:home')
    form = UpdatePostForm(
        initial={
            'content': post.content,
            'image': post.image,
            'category': post.category,
        }
    )
    return render(request, 'posts/edit_post.html', {'form': form, 'post': post})


@login_required(login_url='/accounts/login/')
def post_delete(request, pk):
    post = get_object_or_404(Posts, pk=pk)
    context = {'post': post}
    if request.method == "POST":
        post.delete()
        return redirect('posts:home')
    return render(request, 'posts/delete_post.html', context)


@login_required(login_url='/accounts/login/')
def delete_comment(request, pk):
    comment = get_object_or_404(PostComments, pk=pk)
    context = {}
    if comment.user_id == request.user:
        comment.delete()
        return redirect('posts:home')
    return render(request, 'posts/delete_post.html', context)


@login_required(login_url='/accounts/login/')
def like(request, pk):
    user = User.objects.get(id=request.user.id)
    post = get_object_or_404(Posts, pk=pk)
    liked = False
    like = PostLikes.objects.filter(liker_id=user, post_id=post)
    if like:
        like.delete()
    else:
        liked = True
        PostLikes.objects.create(liker_id=user, post_id=post)
    resp = {
        'liked': liked
    }
    response = json.dumps(resp)
    return HttpResponse(response, content_type="application/json")

posts/templates/posts/create_post.html
{% extends "authentication/header.html" %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<div class="content">
  <div class="content">
    <div class="col-md-8">
      <div class="create_post">
        <form
          class="form-signin"
          method="POST"
          enctype="multipart/form-data"
          action="{% url 'posts:create-post'%}"
        >
          {% csrf_token %}
          <fieldset class="form-group">
            <br />
            {{ form|crispy }}
          </fieldset>
          <div class="form-group">
            <button
              class="btn btn-lg btn-primary btn-block text-uppercase"
              type="submit"
            >
              Post</button
            ><br />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

posts/templates/posts/delete_post.html
{% extends 'authentication/header.html' %}{% block content %}
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you sure you want to delete this post ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'authentication/header.html' %}{% load static %} {% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="row">
        <div class="card-body">
          <h5 class="card-title text-center"><b>Post</b></h5>
          <form class="form-signin" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <br />

              {{ form|crispy }}
            </fieldset>
{% if post.user_id == user %}
            <div class="form-group">

              <button type="submit">Update</button>


            </div>
          </form>

          <form method="POST" action="{% url 'posts:delete' post.id %}">
                        {% csrf_token %}

              <input type="submit" value="Delete" />

            {% endif %}
          </form>

             </div>
  </div>
</div>

{% endblock %}

posts/templates/posts/home.html
{% extends 'authentication/header.html' %} {% load static %} {% load crispy_forms_tags %} {% block content %}

<div class="content">
  <div class="content">
    <div class="col-md-8">
      {% for post in posts %}
      <div class="card card-signin my-5">
        <div class="card-body">
          <a class="text-dark" href="{% url 'authentication:profile_view' post.user_id.username %}">
            {{ post.user_id.username }}</a>
          <br /><small class="text-muted">Posted on {{ post.created_at }}</small>
          <p class="card-text text-dark">{{ post.content }}</p>
        </div>
        {% if post.image %}
        <img src="{{post.image.url}}" alt="" width="150px" height="150px" />
        <br />
        {% else %} {% endif %}

        {% if post.category %}
        <p class="category text-danger ml-3">
          <small>Category: <i>{{ post.category }}</i></small>
        </p>
        {% endif %}
        <div class="card-footer">
          <div class="likes">
            {% if post in liked_post %}
              <a class="btn btn-white mr-3 unlike liker" onclick="liker(event)" href="javascript:void(0);">
                <i class="las la-heart" id="{{ post.id }}"></i>
              </a>
            {% else %}

              <a class="btn btn-white mr-3 like liker" onclick="liker(event)" href="javascript:void(0);">
                <i class="lar la-heart" id="{{ post.id }}"></i>
              </a>
            {% endif %}
            <span class="likes_count" id="post_{{ post.id }}">{{post.likes.count}}</span>
          </div>

        <a class="btn btn-outline-info" href="{% url 'posts:comment' post.id %}">Comments {{ post.details.count }}</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>

{% endblock content %} {% block jsfiles %}
<script type="text/javascript">
  const likeButtons = document.querySelectorAll(".liker");
  const base_url = `${document.location.href}like`;

  function liker(e){
    e = e || window.event; 
    var target = e.target || e.srcElement; 
   // this.preventDefault();
    const id = e.target.id
    fetch(`${base_url}/${id}`)
        .then((response) => response.json())
        .then((data) => {
          console.log(data.liked)
          const likes_count_element = document.querySelector(`#post_${id}`)
          const liker_element = document.getElementById(`${id}`)
          let likes_count = parseInt(likes_count_element.innerText)
          if (data.liked) {
            likes_count_element.innerText = likes_count + 1
            liker_element.classList.remove('lar')
            liker_element.classList.add('las')
          } else {
            likes_count_element.innerText = likes_count - 1
            liker_element.classList.remove('las')
            liker_element.classList.add('lar')
          }
        });

    //console.log(data.liked);
//    location.reload();
  }

  
</script>
{% endblock jsfiles %}

posts/templates/posts/layout.html
<html>

<head>
  <title>SMA App</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/layout.css' %}" />
</head>

<body>
  <a class="navbar-brand ml-4 mr-4"><b>SMA App</b></a>

  <div class="topnav">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'posts:home' %}">Home</a>
      {% if user.is_authenticated %}
      <a class="nav-item nav-link" href="{% url 'posts:my-profile' %}">My Profile</a>
      <a class="nav-item nav-link" href="{% url 'posts:create-post' %}">Create Post</a>
      <a class="nav-item nav-link" href="{% url 'chat:inbox' %}">Messages</a>
      <a class="nav-item nav-link" href="{% url 'authentication:logout' %}">Logout</a>
      {% endif %}
    </div>
  </div>

  {% for message in messages %}

  <div class="alert alert-success">

    {{ message }}
  </div>
  {% endfor %}
  {% block content %}
  {% endblock %}
  {% block jsfiles %}
  {% endblock jsfiles %}
</body>
<footer class="footer"></footer>

</html>

posts/templates/posts/like_dislike.html
{% if post_is_liked %}
    <button type="submit" name="liker_id" value="{{object.id}}" class="btn btn-info">Unlike</button>
    {% else %}
    <button type="submit" name="liker_id" value="{{object.id}}" class="btn btn-info">Like</button>
    {% endif %}

posts/templates/posts/post_detail.html
{% extends 'authentication/header.html' %} {% load static %} {% load crispy_forms_tags %}
{% block content %}
  <div class="row">
    <div class="col-md-8">
      <div class="card card-signin my-5">
        <div class="card-body">
          {% if post.user_id.avatar %}
          <a href="{{ post.user_name.profile.get_absolute_url }}"><img src="{{ post.user_id.avatar.url }}"
              class="rounded-circle" width="30" height="30" alt="" /></a>
          {% else %}
          <img alt="" width=30px height=30px>
          {% endif %}
          <a class="text-dark" href="{{ post.user_name.profile.get_absolute_url }}"><b>
            {{ post.user_id.username}}</b></a>
          <br /><small class="text-muted">Posted on {{ post.created_at}}</small>
          <br /><br />
          <p class="card-text text-dark">{{ post.content }}</p>
        </div>
        {% if post.image %}
        <a href="{{ post.image.url }}"><img class="card-img-top" src="{{ post.image.url }}" alt="post image" width="150" height="150"/></a>
        {% else %}
        {% if post.category %}
        <br />
        <p class="text-danger ml-3">
          <b>Category: <i>{{ post.category }}</i></b>
        </p>
        {% endif %}
        {% endif %}
        <div class="card-footer">

          {% if post.user_id == user %}
          <a class="btn btn-outline-info mr-3" href="{% url 'posts:update-post' post.id %}">Update</a>
          <a class="btn btn-outline-danger" href="{% url 'posts:delete' post.id %}">Delete</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <br />
  <h4>Comments</h4>
  <div class="row">
    <div class="col-md-8">
      <div class="card card-signin my-5">
        <div class="card-body">
          <form class="form-signin" method="POST" id="post-form">
            {% csrf_token %}
            <fieldset class="form-group">
              <br />
              {{ form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">
                Comment</button><br />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      {% if post.details.all %}
      <div class="card card-signin my-5">
        {% for detail in post.details.all %}
        <div class="card-body">
          {% if detail.user_id.avatar %}
          <a href="{{ detail.username.profile.get_absolute_url }}">
            <img src="{{ detail.user_id.avatar.url }}" class="rounded-circle" width="30" height="30" alt="" />
          </a>
          {% else %}
          <img alt="" width=30px height=30px>
          {% endif %}
          <a class="text-dark" href="{{ detail.username.profile.get_absolute_url }}">
            <b>
              {{ detail.user_id.username}}</b></a>
          <br /><small>{{ detail.created_at }}</small><br /><br />
          <p class="card-text text-dark">{{ detail.content }}</p>
          {% if post.user_id == user %}
          <a class="btn btn-outline-danger" href="{% url 'posts:delete-comment' detail.id %}">Delete</a>
          {% endif %}
        </div>
        <hr class="my-1" />
        {% endfor %}
      </div>
      {% else %}
      <p>No comments to show!</p>
      {% endif %}
    </div>
  </div>

{% endblock content %}

posts/templates/posts/user_post.html
{% extends 'authentication/header.html' %}{% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/layout.css' %}">
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div>
        <h3>My Posts
      </div>
      <br>
      {% for post in posts %}
      <div class="card card-signin my-5">
        <div class="card-body">
          <a class="text-dark" >
            {{ post.user_id.username }}</a>
          <br /><small class="text-muted">Posted on {{ post.created_at }}</small>
          <p class="card-text text-dark">{{ post.content }}</p>
        </div>
        {% if post.image %}
        <img src="{{post.image.url}}" alt="" width="150px" height="150px" />
        <br />
        {% else %} {% endif %}

        {% if post.category %}
        <p class="category text-danger ml-3">
          <small>Category: <i>{{ post.category }}</i></small>
        </p>
        {% endif %}
        <div class="card-footer">
          <div class="likes">
            {% if post in liked_post %}
            <a class="btn btn-white mr-3 unlike liker" onclick="liker(event)" href="javascript:void(0);">
              <i class="las la-heart" id="{{ post.id }}"></i>
            </a>
            {% else %}

            <a class="btn btn-white mr-3 like liker" onclick="liker(event)" href="javascript:void(0);">
              <i class="lar la-heart" id="{{ post.id }}"></i>
            </a>
            {% endif %}
            <span class="likes_count" id="post_{{ post.id }}">{{post.likes.count}}</span>
          </div>

          <a class="btn btn-outline-info" href="{% url 'posts:comment' post.id %}">Comments {{ post.details.count }}</a>
        </div>
        {% if post.user_id == user %}
        <span><a class="btn btn-outline-info mr-3" href="{% url 'posts:update-post' post.id %}">Update</a>
       <a class="btn btn-outline-danger" href="{% url 'posts:delete' post.id %}">Delete</a></span>  
          {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
</div>

{% endblock content %}

posts/templates/posts/user_post_backup.html
{% extends "authentication/header.html" %} {% load static %} {% block searchform %}
<form
  class="form-inline my-2 my-lg-0 ml-5"
  action="{% url 'search_users' %}"
  method="get"
>
  <input name="q" type="text" placeholder="Search users.." />
  <button class="btn btn-success my-2 my-sm-0 ml-4" type="submit">
    Search
  </button>
</form>
{% endblock searchform %} {% block content %}
<br /><br />
<div class="main-content">
  <div class="container mt-7">
    <div class="row">
      <div class="col-xl-8 m-auto order-xl-2 mb-5 mb-xl-0">
        <div class="card card-profile shadow">
          <div class="row justify-content-center">
            <div class="col-lg-3 order-lg-2">
              <div class="card-profile-image">
                <a href="{{ u.profile.image.url }}">
                  <img
                    src="{{ u.profile.image.url }}"
                    class="rounded-circle"
                    width="160px"
                    height="160px"
                  />
                </a>
              </div>
            </div>
          </div>
          <div
            class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4"
          ></div>
          <div class="card-body pt-0 pt-md-4">
            <div class="row">
              <div class="col">
                <div
                  class="card-profile-stats d-flex justify-content-center mt-md-5"
                >
                  <div>
                    <span class="heading">{{ u.profile.friends.count }}</span>
                    {% if request.user == u %}
                    <span class="description"
                      ><a href="{% url 'friend_list' %}">Friends</a></span
                    >
                    {% else %}
                    <span class="description">Friends</span>
                    {% endif %}
                    <span class="heading">{{ post_count }}</span>
                    <span class="description"
                      ><a href="{% url 'user-posts' u.username %}"
                        >Posts</a
                      ></span
                    >
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center">
              <h3>{{ u }}</h3>
              <p>{{ u.profile.bio }}</p>
              <hr class="my-2" />
              {% if request.user == u %}
              <a class="btn btn-info" href="{% url 'edit_profile' %}"
                >Edit Profile</a
              >
              {% else %} {% if button_status == 'not_friend' %}
              <small
                ><a
                  class="btn btn-primary"
                  href="/users/friend-request/send/{{ u.id }}"
                  >Add Friend</a
                ></small
              >
              {% elif button_status == 'friend_request_sent' %}
              <small
                ><a
                  class="btn btn-warning"
                  href="/users/friend-request/cancel/{{ u.id }}"
                  >Cancel Request</a
                ></small
              >
              {% elif button_status == 'friend_request_received' %}
              <small
                ><a
                  class="btn btn-success mr-2"
                  href="/users/friend-request/accept/{{ u.id }}"
                  >Accept Request</a
                ></small
              >
              <small
                ><a
                  class="btn btn-danger"
                  href="/users/friend-request/delete/{{ u.id }}"
                  >Reject Request</a
                ></small
              >
              {% else %}
              <small
                ><a
                  class="btn btn-danger"
                  href="/users/friend/delete/{{ u.id }}"
                  >UnFriend</a
                ></small
              >
              {% endif %} {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <br />
    {% if request.user == u %}
    <div class="row">
      <div class="col-md-6">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h2>Friend Requests Sent ({{ sent_friend_requests.count }})</h2>
            <hr class="my-2" />
            {% if not sent_friend_requests %}
            <h5><i>No sent requests!</i></h5>
            {% else %} {% for s_request in sent_friend_requests %}
            <a href="{{ s_request.to_user.profile.get_absolute_url }}"
              ><img
                src="{{ s_request.to_user.profile.image.url }}"
                class="rounded mr-2"
                width="40"
                height="40"
                alt=""
            /></a>
            <a href="{{ s_request.to_user.profile.get_absolute_url }}"
              ><b>{{ s_request.to_user.username }}</b></a
            >
            <small class="float-right">
              <a
                class="btn btn-warning mr-2"
                href="{% url 'cancel_friend_request' s_request.to_user.id %}"
                >Cancel</a
              >
            </small>
            <br /><br />
            {% endfor %} {% endif %}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h2>Friend Requests Recieved ({{ rec_friend_requests.count }})</h2>
            <hr class="my-2" />
            {% if not rec_friend_requests %}
            <h5><i>No recieved requests!</i></h5>
            {% else %} {% for r_request in rec_friend_requests %}
            <a href="{{ r_request.from_user.profile.get_absolute_url }}"
              ><img
                src="{{ r_request.from_user.profile.image.url }}"
                class="rounded mr-2"
                width="40"
                height="40"
                alt=""
            /></a>
            <a
              class="mr-2 align-middle"
              href="{{ r_request.from_user.profile.get_absolute_url }}"
              ><b>{{ r_request.from_user.username }}</b>
            </a>
            <small class="float-right">
              <a
                class="btn btn-success mr-2"
                href="/users/friend-request/accept/{{ r_request.from_user.id }}"
                >Accept</a
              >
              <a
                class="btn btn-danger"
                href="/users/friend-request/delete/{{ r_request.from_user.id }}"
                >Reject</a
              >
            </small>
            <br /><br />
            {% endfor %} {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>

{% endblock content %}